### PR TITLE
Adding ROS Bridge  

### PR DESCRIPTION
**Pull request by BoSmallEar**
## What changes do you make in this PR?

Add ROS2 bridge to MetaDrive

## Checklist

* [x] I have merged the latest main branch into current branch. Yes
* [x] I have run `bash scripts/format.sh` before merging. Yes
* Please use "squash and merge" mode.

### CODE REVIEW

**Review by QuanyiLi — APPROVED** [review]

**Comment by QuanyiLi** [comment]
I reformatted the code and merged the main. Please pull the latest version before further action.

Besides, this could be useful for testing ros2 with github actions: https://github.com/ros-tooling/setup-ros

**Comment by QuanyiLi** [comment]
I get this error when running `rosdep install --from-paths src --ignore-src -y`: 
```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
metadrive_example_bridge: Cannot locate rosdep definition for [vision_msgs_rviz_plugins]

```
It seems a plugin is missing. Is the plugin this one: https://github.com/NovoG93/vision_msgs_rviz_plugins ?

**Comment by BoSmallEar** [comment]
> I get this error when running `rosdep install --from-paths src --ignore-src -y`:
> 
> ```
> ERROR: the following packages/stacks could not have their rosdep keys resolved
> to system dependencies:
> metadrive_example_bridge: Cannot locate rosdep definition for [vision_msgs_rviz_plugins]
> ```
> 
> It seems a plugin is missing. Is the plugin this one: https://github.com/NovoG93/vision_msgs_rviz_plugins ?

Have you run `rosdep update` before `rosdep install`?

**Comment by QuanyiLi** [comment]
Removed the line but got a new error:
```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies (ROS distro is not set. Make sure `ROS_DISTRO` environment variable is set, or use `--rosdistro` option to specify the distro, e.g. `--rosdistro indigo`):
metadrive_example_bridge: Cannot locate rosdep definition for [vision_msgs]

```

**Comment by BoSmallEar** [comment]
I forgot to add `source /opt/ros/humble/setup.bash` in the readme, fixed it now

**Comment by QuanyiLi** [comment]
Cool! I managed to run it! But there is still a plugin missing error:
```
[obj_bridge-3] Traceback (most recent call last):
[obj_bridge-3]   File "/mnt/data/metadrive/bridges/ros_bridge/install/metadrive_example_bridge/lib/metadrive_example_bridge/obj_bridge", line 11, in <module>
[obj_bridge-3]     load_entry_point('metadrive-example-bridge==0.0.0', 'console_scripts', 'obj_bridge')()
[obj_bridge-3]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
[obj_bridge-3]     return get_distribution(dist).load_entry_point(group, name)
[obj_bridge-3]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
[obj_bridge-3]     return ep.load()
[obj_bridge-3]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
[obj_bridge-3]     return self.resolve()
[obj_bridge-3]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
[obj_bridge-3]     module = __import__(self.module_name, fromlist=['__name__'], level=0)
[obj_bridge-3]   File "/mnt/data/metadrive/bridges/ros_bridge/install/metadrive_example_bridge/lib/python3.8/site-packages/metadrive_example_bridge/obj_bridge.py", line 7, in <module>
[obj_bridge-3]     from vision_msgs.msg import BoundingBox3DArray, BoundingBox3D
[obj_bridge-3] ImportError: cannot import name 'BoundingBox3DArray' from 'vision_msgs.msg' (/opt/ros/foxy/lib/python3.8/site-packages/vision_msgs/msg/__init__.py)
[ERROR] [obj_bridge-3]: process has died [pid 29501, exit code 1, cmd '/mnt/data/metadrive/bridges/ros_bridge/install/metadrive_example_bridge/lib/metadrive_example_bridge/obj_bridge --ros-args -r __node:=obj_bridge'].
[rviz2-4] [INFO] [1697741130.111332014] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-4] [INFO] [1697741130.111577379] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[rviz2-4] [INFO] [1697741130.147372725] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-4] [ERROR] [1697741130.224865419] [rviz2]: PluginlibFactory: The plugin for class 'vision_msgs/BoundingBox3DArray' failed to load. Error: According to the loaded plugin descriptions the class vision_msgs/BoundingBox3DArray with base class type rviz_common::Display does not exist. Declared types are  rviz_default_plugins/Axes rviz_default_plugins/Camera rviz_default_plugins/FluidPressure rviz_default_plugins/Grid rviz_default_plugins/GridCells rviz_default_plugins/Illuminance rviz_default_plugins/Image rviz_default_plugins/InteractiveMarkers rviz_default_plugins/LaserScan rviz_default_plugins/Map rviz_default_plugins/Marker rviz_default_plugins/MarkerArray rviz_default_plugins/Odometry rviz_default_plugins/Path rviz_default_plugins/PointCloud rviz_default_plugins/PointCloud2 rviz_default_plugins/PointStamped rviz_default_plugins/Polygon rviz_default_plugins/Pose rviz_default_plugins/PoseArray rviz_default_plugins/PoseWithCovariance rviz_default_plugins/Range rviz_default_plugins/RelativeHumidity rviz_default_plugins/RobotModel rviz_default_plugins/TF rviz_default_plugins/Temperature rviz_default_plugins/Wrench
[rviz2-4] [ERROR] [1697741130.239145525] [rviz2]: PluginlibFactory: The plugin for class 'rviz_common/Time' failed to load. Error: According to the loaded plugin descriptions the class rviz_common/Time with base class type rviz_common::Panel does not exist. Declared types are 
[rviz2-4] [INFO] [1697741130.260314881] [rviz2]: Stereo is NOT SUPPORTED
``` 
How can I resolve this? Once things are ready, I can add the test for this feature.

**Comment by BoSmallEar** [comment]
Probably running 'source /opt/ros/humble/setup.bash' again would work?

**Comment by QuanyiLi** [comment]
I am using foxy instead of humble. I checked the source code of my `vision_msgs`. Indeed, there is no `BounbingBox3DArray` but only `BounbingBox3D`.  Is this a new feature only availabe on Ubuntu22.04 with ros2 humble?

**Comment by BoSmallEar** [comment]
That's weird, according to. `https://github.com/ros-perception/vision_msgs/blob/foxy/vision_msgs/msg/BoundingBox3DArray.msg` foxy should have the `BoundingBox3DArray` type

**Comment by BoSmallEar** [comment]
currently I'm using the docker environment of ROS2 humble, I could also check if it works with foxy myself

**Comment by QuanyiLi** [comment]
Update to `humble` solves everything!

**Comment by QuanyiLi** [comment]
Finish adding tests for the ROS bridge. Cheers!

**Pull request merged**
