### PR TITLE
Add docstring checker in Workflow

### PR DESCRIPTION
**Pull request by BoSmallEar**
## What changes do you make in this PR?
Add docstring checker for metadrive
Probably we could merge this PR after all the docstrings are implemented
* Please describe why you create this PR

## Checklist

* [x] I have merged the latest main branch into current branch.
* [x] I have run `bash scripts/format.sh` before merging.
* Please use "squash and merge" mode.

### CODE REVIEW

**Comment by pengzhenghao** [comment]
Do we have any tool to auto generate the template of the doctoring?

**Review by pengzhenghao — APPROVED** [review]

**Comment by pengzhenghao** [comment]
image
What  does this mean? Is it expected?

**Comment by BoSmallEar** [comment]
shoud work now, we should also define a threshold on how much coverage improvement could be defined as "passed", currently as long as the ci would pass as long as there is any improvment

**Comment by pengzhenghao** [comment]
I think that’s not the case. We should require the doctoring coverage to be non-decreasing. Instead of asking for improvement in each PR.


Best,
Zhenghao

**Comment by BoSmallEar** [comment]
I totally agree, but isn't the goal of this PR to encourage the coverage little by little after each PR? We could also set a minimum coverage and if the final coverage is greater than this we won't check how the coverage changes from the main branch

**Comment by pengzhenghao** [comment]
I think current one is more practical like a real CI test.

The one you are saying like a little game, which might not be suitable to written into the CI workflow. We can just having several PR to increase the coverage while this might not be reflected as a pass flag in CI. After all the coverage improvement is just a short-term campaign

**Comment by BoSmallEar** [comment]
Yes, that's like an incentive to encourage more docstrings.
No problem, the way you're doing is also completely fine and we just need to setup some plans for improving the docstrings

**Pull request merged**
