### PR TITLE
Fix Xbox controller; introduce Takeover policy w/o brake

### PR DESCRIPTION
**Pull request by pengzhenghao**
## What changes do you make in this PR?

* Please describe why you create this PR

## Checklist

* [x] I have merged the latest main branch into current branch.
* [x] I have run `bash scripts/format.sh` before merging.
* Please use "squash and merge" mode.

### CODE REVIEW

**Comment by pengzhenghao** [comment]
@QuanyiLi could you play with `drive_in_single_agent_env.py` to see if this feels better?

**Comment by QuanyiLi** [comment]
It feels bad when the car drives fast. At least, my performance degrades. Maybe I overfit the old keyboard controller...

**Comment by QuanyiLi** [comment]
It takes so long for the steering wheel to return to the center. It makes the control hard when the speed is high.

**Comment by pengzhenghao** [comment]
Now I've reverted all values to previous version. The key differences:

1. we introduce `space` key to indicate `takeover` when using keyboard
2. A little different behavior on `up` and `down` keys:

If throttle > 0, and you press `down`, we will not set the brake to `-brake_increment`. The original code is:

```python
        elif throttle_brake < 0.:   # WHEN YOU PRESS DOWN KEY
            self.throttle_brake = min(self.throttle_brake, 0.)  # IF throttle>0, IT WILL SET TO 0.
            self.throttle_brake -= self.BRAKE_INCREMENT  # throttle NOW EQUALS brake_increment
```

Instead, in this impl, we use:

```python
        elif down_key_pressed:
            if self.throttle_brake <= 0.0:
                self.throttle_brake -= self.BRAKE_INCREMENT
            else:
                self.throttle_brake -= self.BRAKE_INCREMENT_WHEN_THROTTLE
```

note that     

BRAKE_INCREMENT = 0.5
BRAKE_INCREMENT_WHEN_THROTTLE = 0.5

In this impl, we avoid too large change in the `throttle_brake`.

**Comment by QuanyiLi** [comment]
It is good now.

**Pull request merged**
