### PR TITLE
parameterize + dockerize tests

### PR DESCRIPTION
**Pull request by jnewb1**
## What changes do you make in this PR?

Test other python versions to ensure they don't break, with the goal of supporting 3.12 soon (when some other packages support 3.12)

## Checklist

* [x] I have merged the latest main branch into current branch.
* [x] I have run `bash scripts/format.sh` before merging.
* Please use "squash and merge" mode.

### CODE REVIEW

**Comment by jnewb1** [comment]
Moved the testing environment to docker so we can test all the versions locally. 3.12 currently has some dependency issues.

3.11 setup issues:
https://github.com/metadriverse/metadrive/actions/runs/7661200120/job/20880094031?pr=619#step:3:1122

test_sensors gives a different image output within docker?
https://github.com/metadriverse/metadrive/actions/runs/7661200120/job/20880092338?pr=619

**Comment by pengzhenghao** [comment]
Thank you for initiating this PR! What can I do for you? Is it now supporting newer python version or preparing a docker?

**Comment by jnewb1** [comment]
> Thank you for initiating this PR! What can I do for you? Is it now supporting newer python version or preparing a docker?

for now just preparing docker images so we can test multiple python versions. 3.12 has some dependency issues, I believe ray being one of them

**Comment by QuanyiLi** [comment]
Is there anything I can do to help?

**Comment by jnewb1** [comment]
one this is that it seems the docstring commenter is broken for forks
https://github.com/metadriverse/metadrive/actions/runs/7731719043/job/21080032902?pr=619

**Comment by QuanyiLi** [comment]
@pengzhenghao As you made the docstring commenter, could you take a look at this? I am not familiar with this..

**Comment by pengzhenghao** [comment]
sure! I just removed the docstring commenter.

**Pull request closed without merging**
