### PR TITLE
Fix close and reset issue

### LINKED ISSUE #191: [Bug] env close bug when reset env more than once
Hi, I found a tiny bug when call metadrive env like following code:
```python
env = BaseEnv(BaseEnv.default_config())
env.reset()
env.close()
env.reset()  # bug point
```
In a process, after calling `close` method, `self.engine` is not set to None, so when I call `reset` method twice, it will trigger [this ValueError](https://github.com/metadriverse/metadrive/blob/main/metadrive/envs/base_env.py#L329), can you fix it in future update?

### PR DESCRIPTION
**Pull request by pengzhenghao**
## What changes do you make in this PR?

* Please describe why you create this PR

close #191 

## Checklist

* [x] I have merged the latest main branch into current branch.
* [x] I have run `bash scripts/format.sh` before merging.
* Please use "squash and merge" mode.

### CODE REVIEW

**Comment by pengzhenghao** [comment]
Merge this PR when all tests passed!

**Comment by pengzhenghao** [comment]
@QuanyiLi Opps.. Tests break massively...

**Comment by QuanyiLi** [comment]
Remember to close the environment at the end of each test case. Also, remember to add ```try finally``` so the engine will be closed correctly when some tests are broken.
image

**Comment by QuanyiLi** [comment]
I have run all tests. Merge

**Pull request merged**
