### PR TITLE
Add more description for Waymo dataset

### PR DESCRIPTION
**Pull request by pengzhenghao**
## What changes do you make in this PR?

* Please describe why you create this PR

## Checklist

* [ ] I have merged the latest main branch into current branch.
* [ ] I have run `bash scripts/format.sh` before merging.
* Please use "squash and merge" mode.

### CODE REVIEW

**Comment by pengzhenghao** [comment]
@QuanyiLi 

I find we need to update more information on how to use Waymo dataset.

First, we need to update `drive_in_waymo_env.py` file since it does not include information on how to download and put to where of the waymo dataset.

Second, the `read_data_from_dataset.rst` file in document need to be update.

Thanks!

**Comment by pengzhenghao** [comment]
```python

WAYMO_ENV_CONFIG = dict(
    # ===== Map Config =====
    waymo_data_directory=AssetLoader.file_path("waymo", return_raw_style=False),
    start_case_index=0,
    case_num=100,
    store_map=True,

    # ===== Traffic =====
    no_traffic=False,
    traj_start_index=0,
    traj_end_index=-1,
    replay=True,
    no_static_traffic_vehicle=False,

    # ===== Agent config =====
    vehicle_config=dict(
        lidar=dict(num_lasers=120, distance=50),
        lane_line_detector=dict(num_lasers=12, distance=50),
        side_detector=dict(num_lasers=120, distance=50)
    ),
    use_waymo_observation=True,

    # ===== Reward Scheme =====
    # See: https://github.com/metadriverse/metadrive/issues/283
    success_reward=10.0,
    out_of_road_penalty=10.0,
    crash_vehicle_penalty=10.0,
    crash_object_penalty=1.0,
    driving_reward=1.0,
    speed_reward=0.1,
    use_lateral_reward=False,
    horizon=500,

    # ===== Cost Scheme =====
    crash_vehicle_cost=1.0,
    crash_object_cost=1.0,
    out_of_road_cost=1.0,

    # ===== Termination Scheme =====
    out_of_route_done=False,
    crash_vehicle_done=True,
)
```


We have so many config here, I think we need more docs to describe what they are doing

**Comment by pengzhenghao** [comment]
I also find that `WaymoEnv` has many overlap with `MetaDriveEnv`. Maybe we should merge them?

**Comment by pengzhenghao** [comment]
I remove some config since it seems nobody is using them. Again, WaymoEnv Config need more docs

**Comment by pengzhenghao** [comment]
??

**Comment by QuanyiLi** [comment]
**Do NOT** merge them. When we call MetaDriveEnv, it is synthetic data env using PG/rules. Despite some overlapping content, inheriting from BaseEnv allows a better decomposition.

**Pull request closed without merging**
